export enum ApiFetchEnums {
  YOUR_IN_PROGRESS_RUSHMORE_LIST = "YOUR_IN_PROGRESS_RUSHMORE_LIST",
  YOUR_COMPLETED_RUSHMORE_LIST = "YOUR_COMPLETED_RUSHMORE_LIST",
  FOLLOWING_IN_PROGRESS_RUSHMORE_LIST = "FOLLOWING_IN_PROGRESS_RUSHMORE_LIST",
  FOLLOWING_SOLVED_RUSHMORE_LIST = "FOLLOWING_SOLVED_RUSHMORE_LIST",
  FOLLOWING_LIST = "FOLLOWING_LIST",
  FRIENDS_LIST = "FRIENDS_LIST",
  FOLLOWERS_LIST = "FOLLOWERS_LIST",
  USER_BY_ID = "USER_BY_ID",
  USER_RUSHMORE_LIST = "USER_RUSHMORE_LIST",
}
