export enum ApiFetchEnums {
  RUSHMORE_LIST = "RUSHMORE_LIST",
  YOUR_COMPLETED_RUSHMORE_LIST = "YOUR_COMPLETED_RUSHMORE_LIST",
  FOLLOWING_RUSHMORE_IN_PROGRESS = "FOLLOWING_RUSHMORE_IN_PROGRESS",
  FOLLOWING_LIST = "FOLLOWING_LIST",
  FRIENDS_LIST = "FRIENDS_LIST",
  FOLLOWERS_LIST = "FOLLOWERS_LIST",
}
